export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const RESET_PRICE = 'RESET_PRICE'

export const SET_ORDERS = 'SET_ORDERS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH'